csm_localization_node:
  ros__parameters:
    # Localization mode parameters
    pose_graph_input_path: /home/nk/personal_ws/slam/dataset/revo_lds/revo_lds_pose_graph.pg

    # Map building parameters
    fine_resolution: 0.05
    coarse_resolution: 0.1

    # Publish topic
    map_topic: "/map"
    pub_odom_topic: "/slam_odom"

    # transform parameters
    base_link_name: "base_link"
    map_frame_name: "map"
    odom_frame_name: "odom"

    # publish parameters
    publish_base_to_map_transform: true
    publish_map: true
    
    # Subscribe topic
    odom_topic: "odom"
    lidar_topic: "horizontal_laser_2d"
    initial_pose_topic: "initialpose"

    # Subscribe topic type
    # lidar_type: "MultiEchoLaserScan"
    lidar_type: "LaserScan"

    # scan to map matching parameters for localization
    search_distance: 0.1
    search_angle: 15
    search_factor: 5

